# Form implementation generated from reading ui file 'FlightDemo.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog
FONT=QtGui.QFont("Arial",10,QtGui.QFont.Weight.Bold)
LBL_FONT=QtGui.QFont("Times",10,QtGui.QFont.Weight.Bold,True)
class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(449, 321)
        Dialog.setStyleSheet("QDialog{background-color:yellow}\n"
"QLabel{color:darkblue}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        # font = QtGui.QFont()
        # font.setPointSize(10)
        # font.setBold(True)
        # font.setWeight(75)
        self.label.setFont(LBL_FONT)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rdbtn_first = QtWidgets.QRadioButton(Dialog)
        self.rdbtn_first.toggled.connect(self.selected_fligth)
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(9)
        # font.setBold(True)
        # font.setWeight(75)
        self.rdbtn_first.setFont(FONT)
        self.rdbtn_first.setObjectName("rdbtn_first")
        self.verticalLayout.addWidget(self.rdbtn_first)
        self.rdbtn_buss = QtWidgets.QRadioButton(Dialog)
        self.rdbtn_buss.toggled.connect(self.selected_fligth)
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(9)
        # font.setBold(True)
        # font.setWeight(75)
        self.rdbtn_buss.setFont(FONT)
        self.rdbtn_buss.setObjectName("rdbtn_buss")
        self.verticalLayout.addWidget(self.rdbtn_buss)
        self.rdbtn_econ = QtWidgets.QRadioButton(Dialog)
        self.rdbtn_econ.toggled.connect(self.selected_fligth)
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(9)
        # font.setBold(True)
        # font.setWeight(75)
        self.rdbtn_econ.setFont(FONT)
        self.rdbtn_econ.setObjectName("rdbtn_econ")
        self.verticalLayout.addWidget(self.rdbtn_econ)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.lbl_result = QtWidgets.QLabel(Dialog)
        self.lbl_result.setFont(LBL_FONT)
        self.lbl_result.setObjectName("lbl_result")
        self.verticalLayout_2.addWidget(self.lbl_result)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Select Flight Type"))
        self.rdbtn_first.setText(_translate("Dialog", "First Class  $150"))
        self.rdbtn_buss.setText(_translate("Dialog", "Business Class $120"))
        self.rdbtn_econ.setText(_translate("Dialog", "Economy Class $80"))
        self.lbl_result.setText(_translate("Dialog", ""))

    def selected_fligth(self):
        flight=self.sender()
        if flight.isChecked():
            self.lbl_result.setText("You selected {}".format(flight.text()))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
