# Form implementation generated from reading ui file 'RadioDemo.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import time

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog

LBL_FONT = QtGui.QFont("Times", 10, QtGui.QFont.Weight.Bold, True)
FONT = QtGui.QFont("Arial", 10, QtGui.QFont.Weight.Bold)


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(525, 390)
        icon = QtGui.QIcon("../images/computer.png")
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("QLabel{color:purple}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 161, 31))
        self.label.setFont(LBL_FONT)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 291, 31))
        self.label_2.setFont(LBL_FONT)
        self.label_2.setObjectName("label_2")
        self.lbl_result = QtWidgets.QLabel(Dialog)
        self.lbl_result.setGeometry(QtCore.QRect(30, 335, 471, 31))
        self.lbl_result.setFont(LBL_FONT)
        self.lbl_result.setObjectName("lbl_result")

        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 70, 171, 85))
        self.widget.setObjectName("widget")
        self.vbox1 = QtWidgets.QVBoxLayout(self.widget)
        self.vbox1.setContentsMargins(0, 0, 0, 0)
        self.vbox1.setObjectName("vbox1")
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setFont(FONT)
        icon = QtGui.QIcon("../images/python.png")
        self.radioButton.setIcon(icon)
        self.radioButton.setObjectName("radioButton")
        self.radioButton.toggled.connect(self.radio_selected)
        self.vbox1.addWidget(self.radioButton)

        self.rbtn_java = QtWidgets.QRadioButton(self.widget)
        self.rbtn_java.setFont(FONT)
        self.rbtn_java.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        icon = QtGui.QIcon("../images/java.png")
        self.rbtn_java.setIcon(icon)
        self.rbtn_java.setObjectName("rbtn_java")
        self.rbtn_java.toggled.connect(self.radio_selected)
        self.vbox1.addWidget(self.rbtn_java)

        self.rd_jscript = QtWidgets.QRadioButton(self.widget)
        self.rd_jscript.setFont(FONT)
        icon = QtGui.QIcon("../images/javascript.png")
        self.rd_jscript.setIcon(icon)
        self.rd_jscript.setObjectName("rd_jscript")
        self.vbox1.addWidget(self.rd_jscript)

        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(30, 200, 176, 85))
        self.widget1.setObjectName("widget1")
        self.vbox2 = QtWidgets.QVBoxLayout(self.widget1)
        self.vbox2.setContentsMargins(0, 0, 0, 0)
        self.vbox2.setObjectName("vbox2")

        self.rdbtn_card = QtWidgets.QRadioButton(self.widget1)
        self.rdbtn_card.setFont(FONT)
        self.rdbtn_card.setObjectName("rdbtn_card")
        self.rdbtn_card.toggled.connect(self.radio_selected)
        self.vbox2.addWidget(self.rdbtn_card)

        self.rdbtn_paypal = QtWidgets.QRadioButton(self.widget1)
        self.rdbtn_paypal.setFont(FONT)
        self.rdbtn_paypal.setObjectName("rdbtn_paypal")
        self.rdbtn_paypal.toggled.connect(self.radio_selected)
        self.vbox2.addWidget(self.rdbtn_paypal)

        self.rdbtn_cash = QtWidgets.QRadioButton(self.widget1)
        self.rdbtn_cash.setFont(FONT)
        self.rdbtn_cash.setObjectName("rdbtn_cash")
        self.rdbtn_cash.toggled.connect(self.radio_selected)
        self.vbox2.addWidget(self.rdbtn_cash)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Radio Button Example"))
        self.label.setText(_translate("Dialog", "Choose Your Book"))
        self.label_2.setText(_translate("Dialog", "Choose Your Payment Method"))
        self.lbl_result.setText(_translate("Dialog", "Chosen Book:  ---  Chosen Payment Method: "))
        self.radioButton.setText(_translate("Dialog", "Python"))
        self.rbtn_java.setText(_translate("Dialog", "Java"))
        self.rd_jscript.setText(_translate("Dialog", "JavaScript"))
        self.rdbtn_card.setText(_translate("Dialog", "Debit / Credit Card"))
        self.rdbtn_paypal.setText(_translate("Dialog", "PayPal"))
        self.rdbtn_cash.setText(_translate("Dialog", "Money Transfer"))

    def radio_selected(self):
        selected1 = ""
        selected2 = ""
        for i in range(self.vbox1.count()):
            item1 = self.vbox1.itemAt(i).widget()
            if item1.isChecked():
                for i in range(self.vbox2.count()):
                    item2 = self.vbox2.itemAt(i).widget()
                    if item2.isChecked():
                        selected1 = item1.text()
                        selected2 = item2.text()
        # if self.radioButton.isChecked() == True:
        #     selected1 = "Python"
        # if self.rbtn_java.isChecked() == True:
        #     selected1 = "Java"
        # if self.rd_jscript.isChecked() == True:
        #     selected1 = "JavaScript"
        # if self.rdbtn_card.isChecked() == True:
        #     selected2 = "Debit / Credit Card"
        # if self.rdbtn_paypal.isChecked() == True:
        #     selected2 = self.rdbtn_paypal.text()
        # if self.rdbtn_cash.isChecked() == True:
        #     selected2 = self.rdbtn_cash.text()
        # result=[]
        # result.append(selected1)
        # result.append(selected2)
        # self.print_result(result)
        self.lbl_result.setText(f'Chosen Book: {selected1} ---  Chosen Payment Method: {selected2}')

    # def print_result(self,result):
    #     self.lbl_result.setText(f"Chosen Book: {result[0]} and Chosen Payment Method: {result[1]}")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
